import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* ==================================================
                                    NAV
            ==================================================  */}
        <section className={styles.nav}>
          <div className={styles.navSvgContainer}>
            <img
              className={styles.navSvg}
              src="manbypc.svg"
              alt="team img"
            ></img>
            <div className={styles.ieDesignsContainer}>
              <div>IE</div>
              <div>WEBDEVS</div>
            </div>
          </div>
          <div>CONTACT</div>
        </section>
        {/* ==================================================
                                    HERO
            ==================================================  */}
        <section className={styles.hero}>
          <div className={styles.heroBox}>
            <h1>MODERN FULLSTACK WEB DEVELOPMENT</h1>
            <p>Responsive websites, latest technologies, all devices.</p>
            <button className={styles.heroButton}>Lets Work Together</button>
            <div className={styles.svgContainer}>
              <img className={styles.pcSvg} src="undraw1.svg" alt="icon"></img>
            </div>
          </div>
        </section>
        {/* ==================================================
                                    INTRO
            ==================================================  */}
        <section className={styles.intro}>
          <div className={styles.introFirstBox}>
            <h2>MODERN DESIGN</h2>
            <div className={styles.firstBoxSvgs}>
              <div className={styles.responsiveSvgContainer}>
                <img
                  className={styles.responsiveSvg}
                  src="react.svg"
                  alt="icon"
                ></img>
              </div>
              <div className={styles.responsiveSvgContainer}>
                <img
                  className={styles.responsiveSvg}
                  src="nextJs.svg"
                  alt="icon"
                ></img>
              </div>
            </div>
            <p>
              Full Stack Web development and design using the latest
              technologies such as NextJS and React.
            </p>
          </div>
          <div className={styles.introSecondBox}>
            <div className={styles.infoBox}>
              <h3>Fully Responsive</h3>
              <div className={styles.responsiveSvgContainer}>
                <img
                  className={styles.responsiveSvg}
                  src="responsive.svg"
                  alt="icon"
                ></img>
              </div>
              <p>
                Websites that look great on all your favorite devices, whether
                its a phone, pc, or tablet.
              </p>
            </div>
            <div className={styles.infoBox}>
              <h3>Full Stack</h3>
              <div className={styles.responsiveSvgContainer}>
                <img
                  className={styles.responsiveSvg}
                  src="fullStack.svg"
                  alt="icon"
                ></img>
              </div>
              <p>Front End and Back end code.</p>
            </div>
            <div className={styles.infoBox}>
              <h3>Future Web Development in Mind</h3>
              <div className={styles.responsiveSvgContainer}>
                <img
                  className={styles.responsiveSvg}
                  src="team.svg"
                  alt="icon"
                ></img>
              </div>
              <p>Modern and future trends in mind using React and NextJS.</p>
            </div>
          </div>
        </section>
        {/* ==================================================
                                    PORTFOLIO
            ==================================================  */}

        <h2 className={styles.myPortfolioH2}>PROJECTS</h2>
        <div className={styles.responsiveSvgContainer}>
          <img
            className={styles.responsiveSvg}
            src="portfolio.svg"
            alt="icon"
          ></img>
        </div>
        <section className={styles.portfolio}>
          {/* <h2 className={styles.myPortfolioH2}>PROJECTS</h2>
          <div className={styles.responsiveSvgContainer}>
            <img
              className={styles.responsiveSvg}
              src="portfolio.svg"
              alt="icon"
            ></img>
          </div> */}
          <div className={styles.portfolioBox1}>
            <div className={styles.portfolioPng1Container}>
              <img
                className={styles.portfolioPng1}
                src="watchportfolio.png"
                alt="icon"
              ></img>
            </div>
            <h3>Augustus Revinci</h3>
            <p className={styles.subHead}>
              HTML, CSS, Javascript, React, Next JS
            </p>
            <p className={styles.portfolioWebsiteInfo}>
              Augustus Revinci is a watch retail website. The purpose of this
              project was to display a knowledge of
            </p>
            <button className={styles.visitButton}>Visit</button>
          </div>
          <div className={styles.portfolioBox1}>
            <div className={styles.portfolioPng1Container}>
              <img
                className={styles.portfolioPng1}
                src="wscbull.png"
                alt="icon"
              ></img>
            </div>
            <h3>WallStreetChan</h3>
            <p className={styles.subHead}>
              Fullstack, API, ServerSide Fetching, MongoDB
            </p>
            <p className={styles.portfolioWebsiteInfo}>
              WallStreetChan is an investment website where users can share
              opinions and info anonymously.
            </p>
            <button className={styles.visitButton}>Visit</button>
          </div>
          <div className={styles.portfolioBox1}>
            <div className={styles.portfolioPng1Container}>
              <img
                className={styles.portfolioPng1}
                src="esmeraladscake.png"
                alt="icon"
              ></img>
            </div>
            <h3>Esmeraldas</h3>
            <p className={styles.subHead}>
              HTML, CSS, Javascript, React, Next JS
            </p>
            <p className={styles.portfolioWebsiteInfo}>
              Augustus Revinci is a watch retail website. The purpose of this
              project was to display a knowledge of
            </p>
            <button className={styles.visitButton}>Visit</button>
          </div>
        </section>
        {/* ==================================================
                                    MY INFO
            ==================================================  */}
        <section className={styles.myInfo}>
          <h2>WHO I AM</h2>
          <div className={styles.responsiveSvgContainer}>
            <img
              className={styles.responsiveSvg}
              src="hello.svg"
              alt="icon"
            ></img>
          </div>
          <div className={styles.portfolioPng1Container}>
            <img
              className={styles.portfolioPng1}
              src="wscbull.png"
              alt="icon"
            ></img>
          </div>
          <p className={styles.myInfoText}>
            Hello, my name is Pedro. This year I am trying to make a career
            change into web development after years in customer service. Ever
            since high school its been my dream to work with software and I
            finally decided to chase my dream and make it a reality. I thrive in
            team enviroments and would love to become part of yours.
          </p>
          <h4>Pedro C.</h4>
          <h4>Web Developer</h4>
        </section>
      </main>

      {/* ==================================================
                                    FOOTER
            ==================================================  */}

      <footer className={styles.footer}>
        <div className={styles.footerInfoContainer}>
          <div className={styles.footerLogo}>
            <img
              className={styles.footerSvg}
              src="manbypc.svg"
              alt="team img"
            ></img>
            <div className={styles.ieDesignsContainer}>
              <div>IE</div>
              <div>WEBDEVS</div>
            </div>
          </div>
          <p>pedrocruz6427@outlook.com</p>
          <p>909-201-3099</p>
          <p>Github: https://github.com/PedroCruz6427</p>
        </div>
      </footer>
    </>
  );
}
